doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            #Place to add new connections
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true

                mappings:
                    #Add there Entity and VO mappings
                    # App\Users
                    App\Users\Entities:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Users/Entities'
                        prefix: 'App\Users\Entities'
