framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: # TODO: Remove default bus maybe?
            messenger.bus.command:
                middleware:
                    - 'App\Common\CQRS\Middlewares\ValidateCommandMiddleware'
            messenger.bus.query:
                middleware:
                    - 'App\Common\CQRS\Middlewares\ValidateCommandMiddleware'

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: sync://

        routing:
            '*': sync
