version: '3.8'

services:
    nginx:
        image: registry.gitlab.com/rgwsk65-docker/nginx-uid:latest
        ports:
            - 8080:80
        volumes:
            - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:ro
        links:
            - app

    app:
        image: registry.gitlab.com/rgwsk65-docker/php-fpm:8.0
        volumes:
            - ./:/var/www/html
        links:
            - mysql

    mysql:
        image: mysql:8
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=phpexp
            - MYSQL_USER=phpexp
            - MYSQL_PASSWORD=phpexp
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./.docker/mysql/native-password.cnf:/etc/mysql/conf.d/native-password.cnf:ro
            - phpexpdb:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8060:80
        links:
            - mysql:db

volumes:
    phpexpdb:
        external: true
